# Generated by Django 4.1 on 2023-01-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_usermodel_delete_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='phone',
            field=models.IntegerField(default=12345678),
            preserve_default=False,
        ),
    ]
