# Generated by Django 4.1 on 2023-01-01 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0003_usermodel_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
