# Generated by Django 4.1 on 2022-12-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to='../static/assests/product/'),
        ),
    ]
